# Generated by Django 5.0.3 on 2024-03-22 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('temperature', models.DecimalField(decimal_places=1, max_digits=5)),
                ('humidity', models.DecimalField(decimal_places=1, max_digits=5)),
                ('weather', models.CharField(default=0, max_length=10)),
                ('speed', models.CharField(default=0, max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
